//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestingExpressiveAnnotations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhoneData
    {
        public int PhoneDataId { get; set; }
        public int PersonaId { get; set; }
        public string Descripcion { get; set; }
        public string PhoneNumber { get; set; }
    
        public virtual Persona Persona { get; set; }
    }
}
